// The human-readable face of the index.
//
// The generated README is a real awesome-list — browsable, linkable, and
// diffable in git — but every line is derived, so it never drifts from the
// data the way a hand-maintained list does. Dead entries do not linger for
// two years because nobody re-clicked them.

const esc = (s) => String(s || '').replace(/([|\[\]])/g, '\\$1').replace(/\n+/g, ' ').trim();

const MARK = { alive: '', blocked: ' ⚠︎', unknown: ' ?', dead: ' ✗' };

function sectionOf(e) {
  if (e.sections?.length) return e.sections[0];
  if (e.github?.topics?.length) return e.github.topics[0];
  return 'Other';
}

export function renderMarkdown(entries, { title = 'Sifted Resources' } = {}) {
  const groups = new Map();
  for (const e of entries) {
    const g = sectionOf(e);
    if (!groups.has(g)) groups.set(g, []);
    groups.get(g).push(e);
  }
  const ordered = [...groups.entries()].sort((a, b) => b[1].length - a[1].length);

  const lines = [
    `# ${title}`, '',
    `${entries.length} resources, deduplicated across sources and checked for liveness.`,
    `Generated by [sifter](https://github.com/Daily-AC/sifter) on ${new Date().toISOString().slice(0, 10)} — do not edit by hand.`,
    '',
    '| | |', '|---|---|',
    `| ⚠︎ | reachable, but it refuses automated checks |`,
    `| ? | could not be verified on the last run |`,
    '',
  ];

  if (ordered.length > 1) {
    lines.push('## Contents', '');
    for (const [g, items] of ordered) {
      lines.push(`- [${esc(g)}](#${String(g).toLowerCase().replace(/[^\w一-鿿]+/g, '-')}) (${items.length})`);
    }
    lines.push('');
  }

  for (const [g, items] of ordered) {
    lines.push(`## ${esc(g)}`, '');
    items.sort((a, b) => (b.mentions - a.mentions) || ((b.github?.stars || 0) - (a.github?.stars || 0)));
    for (const e of items) {
      const name = esc(e.title || e.names?.[0] || e.key);
      const mark = MARK[e.liveness?.status] ?? '';
      const desc = esc(e.description || e.claims?.[0]?.text || '');
      const meta = [
        e.github?.stars ? `★${e.github.stars.toLocaleString()}` : null,
        e.mentions > 1 ? `${e.mentions} sources` : null,
      ].filter(Boolean).join(' · ');
      lines.push(`- **[${name}](${e.url})**${mark}${desc ? ` — ${desc.slice(0, 180)}` : ''}${meta ? ` <sub>${meta}</sub>` : ''}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}
